spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/community
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: messages, errors
logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.orm.jdbc : trace
    org.hibernate.type.descriptor: trace

